services:
  portfolio:
    build: 
      context: ../..
      dockerfile: deploy/build_img/Dockerfile
    image: iferlop/portfolioreact:v1
    container_name: portfolio_app
    ports: 
      - "8000:80"
    restart: always