apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-ismael
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Vixtinity/portfolioreact.git
    targetRevision: main
    path: deploy/miportfolio
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true