apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-portfolio
  namespace: portfolio-namespace
  rollout-date: {{ now | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miportfolio
  template:
    metadata:
      labels:
        app: miportfolio
    spec:
      volumes:
        - name: logs
          hostPath:
            path: /var/log/miportfolio 
            type: DirectoryOrCreate
      containers:
        - name: miportfolio
          image: iferlop/portfolio_app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: logs
              mountPath: /var/log/nginx
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"