apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-portfolio
  namespace: portfolio-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miportfolio
  template:
    metadata:
      labels:
        app: miportfolio
    spec:
      volumes:
        - name: logs
          hostPath:
            path: /var/log/miportfolio 
            type: DirectoryOrCreate
      containers:
        - name: miportfolio
          image: iferlop/portfolioreact:00c1d49d920293c4519d167b06643cc068ed01ab
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: logs
              mountPath: /var/log/nginx
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"