apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-miportfolio
  namespace: portfolio-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: www.IsmaelF.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-miportfolio
                port:
                  number: 80